---
title: "ANOVAmodel_variable_combinations"
output: html_document
date: "2026-04-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# no ChHlthSt_2324
```{r}
library(ggplot2)
library(GGally)

no_ChHlth_model <- lm(grades_2324 ~ 1 
+LowBWght_2324+PhysAct_2324+Cond2more_2324+CSHCN_2324+ADHDind_2324+ADHDSevInd_2324 + +bullied_2324+bully_2324+MakeFriend_2324+MEDB10ScrQ5_2324+povlev4_2324+FoodSit_2324+FoodCash_2324+HousingInstab_2324 + famstruct5_2324+age5_2324+sex_2324+MedCare_2324+MentHCare_2324+SpEducPln_2324+ReptGrade_2324, data = df_23_24_clean)

anova(no_ChHlth_model)

# R- Squared Value
summary(no_ChHlth_model)$r.squared 
summary(no_ChHlth_model)$adj.r.squared
```
# no LowBWght_2324
```{r}
no_LowBWght_model <- lm(grades_2324 ~ 1 
+ChHlthSt_2324+PhysAct_2324+Cond2more_2324+CSHCN_2324+ADHDind_2324+ADHDSevInd_2324 + +bullied_2324+bully_2324+MakeFriend_2324+MEDB10ScrQ5_2324+povlev4_2324+FoodSit_2324+FoodCash_2324+HousingInstab_2324 + famstruct5_2324+age5_2324+sex_2324+MedCare_2324+MentHCare_2324+SpEducPln_2324+ReptGrade_2324, data = df_23_24_clean)

anova(no_LowBWght_model)

# R- Squared Value
summary(no_LowBWght_model)$r.squared 
summary(no_LowBWght_model)$adj.r.squared 
```
# no PhysAct_2324
```{r}
no_PhysAct_model <- lm(grades_2324 ~ 1 
+ChHlthSt_2324+LowBWght_2324+Cond2more_2324+CSHCN_2324+ADHDind_2324+ADHDSevInd_2324 + +bullied_2324+bully_2324+MakeFriend_2324+MEDB10ScrQ5_2324+povlev4_2324+FoodSit_2324+FoodCash_2324+HousingInstab_2324 + famstruct5_2324+age5_2324+sex_2324+MedCare_2324+MentHCare_2324+SpEducPln_2324+ReptGrade_2324, data = df_23_24_clean)

anova(no_PhysAct_model)

# R- Squared Value
summary(no_PhysAct_model)$r.squared 
summary(no_PhysAct_model)$adj.r.squared 
```
# no Cond2more_2324
```{r}
no_Cond2more_model <- lm(grades_2324 ~ 1 
+ChHlthSt_2324+LowBWght_2324+PhysAct_2324+CSHCN_2324+ADHDind_2324+ADHDSevInd_2324 + +bullied_2324+bully_2324+MakeFriend_2324+MEDB10ScrQ5_2324+povlev4_2324+FoodSit_2324+FoodCash_2324+HousingInstab_2324 + famstruct5_2324+age5_2324+sex_2324+MedCare_2324+MentHCare_2324+SpEducPln_2324+ReptGrade_2324, data = df_23_24_clean)

anova(no_Cond2more_model)

# R- Squared Value
summary(no_Cond2more_model)$r.squared 
summary(no_Cond2more_model)$adj.r.squared 
```

# no CSHCN_2324
```{r}
no_CSHCN_model <- lm(grades_2324 ~ 1 
+ChHlthSt_2324+LowBWght_2324+PhysAct_2324+Cond2more_2324+ADHDind_2324+ADHDSevInd_2324 + +bullied_2324+bully_2324+MakeFriend_2324+MEDB10ScrQ5_2324+povlev4_2324+FoodSit_2324+FoodCash_2324+HousingInstab_2324 + famstruct5_2324+age5_2324+sex_2324+MedCare_2324+MentHCare_2324+SpEducPln_2324+ReptGrade_2324, data = df_23_24_clean)

anova(no_CSHCN_model)

# R- Squared Value
summary(no_CSHCN_model)$r.squared 
summary(no_CSHCN_model)$adj.r.squared 
```

# no bullied_2324
```{r}
no_bullied_model <- lm(grades_2324 ~ 1 
+ChHlthSt_2324+LowBWght_2324+PhysAct_2324+Cond2more_2324+CSHCN_2324+ADHDind_2324+ADHDSevInd_2324 + +bully_2324+MakeFriend_2324+MEDB10ScrQ5_2324+povlev4_2324+FoodSit_2324+FoodCash_2324+HousingInstab_2324 + famstruct5_2324+age5_2324+sex_2324+MedCare_2324+MentHCare_2324+SpEducPln_2324+ReptGrade_2324, data = df_23_24_clean)

anova(no_bullied_model)

# R- Squared Value
summary(no_bullied_model)$r.squared 
summary(no_bullied_model)$adj.r.squared 
```

# no bully_2324
```{r}
no_bully_model <- lm(grades_2324 ~ 1 
+ChHlthSt_2324+LowBWght_2324+PhysAct_2324+Cond2more_2324+CSHCN_2324+ADHDind_2324+ADHDSevInd_2324 + +bullied_2324+MakeFriend_2324+MEDB10ScrQ5_2324+povlev4_2324+FoodSit_2324+FoodCash_2324+HousingInstab_2324 + famstruct5_2324+age5_2324+sex_2324+MedCare_2324+MentHCare_2324+SpEducPln_2324+ReptGrade_2324, data = df_23_24_clean)

anova(no_bully_model)

# R- Squared Value
summary(no_bully_model)$r.squared 
summary(no_bully_model)$adj.r.squared 
```

# no MakeFriend_2324
```{r}
no_MakeFriend_model <- lm(grades_2324 ~ 1 
+ChHlthSt_2324+LowBWght_2324+PhysAct_2324+Cond2more_2324+CSHCN_2324+ADHDind_2324+ADHDSevInd_2324 + +bullied_2324+bully_2324+MEDB10ScrQ5_2324+povlev4_2324+FoodSit_2324+FoodCash_2324+HousingInstab_2324 + famstruct5_2324+age5_2324+sex_2324+MedCare_2324+MentHCare_2324+SpEducPln_2324+ReptGrade_2324, data = df_23_24_clean)

anova(no_MakeFriend_model)

# R- Squared Value
summary(no_MakeFriend_model)$r.squared 
summary(no_MakeFriend_model)$adj.r.squared 
```

# no MEDB10ScrQ5_2324
```{r}
no_MEDB10ScrQ5_model <- lm(grades_2324 ~ 1 
+ChHlthSt_2324+LowBWght_2324+PhysAct_2324+Cond2more_2324+CSHCN_2324+ADHDind_2324+ADHDSevInd_2324 + +bullied_2324+bully_2324+MakeFriend_2324+povlev4_2324+FoodSit_2324+FoodCash_2324+HousingInstab_2324 + famstruct5_2324+age5_2324+sex_2324+MedCare_2324+MentHCare_2324+SpEducPln_2324+ReptGrade_2324, data = df_23_24_clean)

anova(no_MEDB10ScrQ5_model)

# R- Squared Value
summary(no_MEDB10ScrQ5_model)$r.squared 
summary(no_MEDB10ScrQ5_model)$adj.r.squared 
```

# no povlev4_2324
```{r}
no_povlev4_model <- lm(grades_2324 ~ 1 
+ChHlthSt_2324+LowBWght_2324+PhysAct_2324+Cond2more_2324+CSHCN_2324+ADHDind_2324+ADHDSevInd_2324 + +bullied_2324+bully_2324+MakeFriend_2324+MEDB10ScrQ5_2324+FoodSit_2324+FoodCash_2324+HousingInstab_2324 + famstruct5_2324+age5_2324+sex_2324+MedCare_2324+MentHCare_2324+SpEducPln_2324+ReptGrade_2324, data = df_23_24_clean)

anova(no_povlev4_model)

# R- Squared Value
summary(no_povlev4_model)$r.squared 
summary(no_povlev4_model)$adj.r.squared 
```


# no MedCare_2324
```{r}
no_MedCare_model <- lm(grades_2324 ~ 1 
+ChHlthSt_2324+LowBWght_2324+PhysAct_2324+Cond2more_2324+CSHCN_2324+ADHDind_2324+ADHDSevInd_2324 + +bullied_2324+bully_2324+MakeFriend_2324+MEDB10ScrQ5_2324+FoodSit_2324+FoodCash_2324+HousingInstab_2324 + famstruct5_2324+age5_2324+sex_2324+povlev4_2324+MentHCare_2324+SpEducPln_2324+ReptGrade_2324, data = df_23_24_clean)

anova(no_MedCare_model)

# R- Squared Value
summary(no_MedCare_model)$r.squared 
summary(no_MedCare_model)$adj.r.squared 
```

# no MentHCare_2324
```{r}
no_MentHCare_model <- lm(grades_2324 ~ 1 
+ChHlthSt_2324+LowBWght_2324+PhysAct_2324+Cond2more_2324+CSHCN_2324+ADHDind_2324+ADHDSevInd_2324 + +bullied_2324+bully_2324+MakeFriend_2324+MEDB10ScrQ5_2324+FoodSit_2324+FoodCash_2324+HousingInstab_2324 + famstruct5_2324+age5_2324+sex_2324+povlev4_2324+MedCare_2324+SpEducPln_2324+ReptGrade_2324, data = df_23_24_clean)

anova(no_MentHCare_model)

# R- Squared Value
summary(no_MentHCare_model)$r.squared 
summary(no_MentHCare_model)$adj.r.squared 
```

# no SpEducPln_2324
```{r}
no_SpEducPln_model <- lm(grades_2324 ~ 1 
+ChHlthSt_2324+LowBWght_2324+PhysAct_2324+Cond2more_2324+CSHCN_2324+ADHDind_2324+ADHDSevInd_2324 + +bullied_2324+bully_2324+MakeFriend_2324+MEDB10ScrQ5_2324+FoodSit_2324+FoodCash_2324+HousingInstab_2324 + famstruct5_2324+age5_2324+sex_2324+povlev4_2324+MedCare_2324+MentHCare_2324+ReptGrade_2324, data = df_23_24_clean)

anova(no_SpEducPln_model)

# R- Squared Value
summary(no_SpEducPln_model)$r.squared 
summary(no_SpEducPln_model)$adj.r.squared 
```

# no ReptGrade_2324
```{r}
no_ReptGrade_model <- lm(grades_2324 ~ 1 
+ChHlthSt_2324+LowBWght_2324+PhysAct_2324+Cond2more_2324+CSHCN_2324+ADHDind_2324+ADHDSevInd_2324 + +bullied_2324+bully_2324+MakeFriend_2324+MEDB10ScrQ5_2324+FoodSit_2324+FoodCash_2324+HousingInstab_2324 + famstruct5_2324+age5_2324+sex_2324+povlev4_2324+MedCare_2324+MentHCare_2324+SpEducPln_2324, data = df_23_24_clean)

anova(no_ReptGrade_model)

# R- Squared Value
summary(no_ReptGrade_model)$r.squared 
summary(no_ReptGrade_model)$adj.r.squared 
```

# no HounsingInstab_2324
```{r}
no_HousingInstab_model <- lm(grades_2324 ~ 1 
+ChHlthSt_2324+LowBWght_2324+PhysAct_2324+Cond2more_2324+CSHCN_2324+ADHDind_2324+ADHDSevInd_2324 + +bullied_2324+bully_2324+MakeFriend_2324+MEDB10ScrQ5_2324+FoodSit_2324+FoodCash_2324+ReptGrade_2324 + famstruct5_2324+age5_2324+sex_2324+povlev4_2324+MedCare_2324+MentHCare_2324+SpEducPln_2324, data = df_23_24_clean)

anova(no_HousingInstab_model)

# R- Squared Value
summary(no_HousingInstab_model)$r.squared 
summary(no_HousingInstab_model)$adj.r.squared 
```