---
title: "null_model"
output: html_document
date: "2026-04-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Add factors on, see resulting R Squared Value
```{r}
library(purrr)
library(broom)

vars <- c("df_23_24_clean$FoodSit_2324", "df_23_24_clean$povlev4_2324", "df_23_24_clean$ADHDSevInd_2324", "df_23_24_clean$LowBWght_2324", "df_23_24_clean$Cond2more_2324", "df_23_24_clean$MentHCare_2324")

models <- map(seq_along(vars), ~ lm(
  as.formula(paste("df_23_24_clean$grades_2324 ~", paste(vars[1:.x], collapse = " + "))),
  data = df_23_24_clean
))

results <- map_dfr(models, glance)

results$r.squared
```


# Less successful model, focuses on AIC instead of R squared
## Null Model

```{r}
library(MASS)
y<- df_23_24_clean$grades_2324
x1<-df_23_24_clean$FoodSit_2324
x2<-df_23_24_clean$povlev4_2324
x3<-df_23_24_clean$ADHDSevInd_2324
x4<-df_23_24_clean$LowBWght_2324
x5<-df_23_24_clean$Cond2more_2324
x6<-df_23_24_clean$MentHCare_2324
null <- lm(null <- lm(y ~ x1 + x2))
alt <- addterm(null, ~. + x1*x2 + (x1^2) + (x2^2) + (x1^2)*x2 + (x2^2)*x1 + (x1^2)*(x2^2))
alt$AIC

# R- Squared Value
summary(null)$r.squared 
summary(null)$adj.r.squared
```

```{r}
library(MASS)

povertylevel_model <- lm(grades_2324 ~ 1,data = df_23_24_clean)

anova(povertylevel_model)

#step(null_model)

null <- lm(null <- lm(grades_2324 ~povlev4_2324+FoodSit_2324, data = df_23_24_clean))
alt <- addterm(null, ~. + povlev4*FoodSit_2324 + FoodSit_2324, data = df_23_24_clean)

# R- Squared Value
#summary(null)$r.squared 
#summary(null)$adj.r.squared

alt <- addterm(null, ~. + x1*x2 + I(x1^2) + I(x2^2) + I(x1^2)*x2 + I(x2^2)*x1 + I(x1^2)*I(x2^2))
alt$AIC
```

